name: 'Publish VS Code Extensions'
description: 'Publishes VS Code extensions to marketplace with version checking and robust error handling'
inputs:
  marketplace:
    description: 'Target marketplace (vscode or vscodium)'
    required: true
  packages-path:
    description: 'Path to packages directory (e.g., packages/vscode or packages/vscodium)'
    required: true
  dist-path:
    description: 'Path to dist directory containing .vsix files'
    required: true
    default: 'dist'
  vsce-token:
    description: 'VS Code Marketplace Personal Access Token'
    required: false
  ovsx-token:
    description: 'Open VSX Registry Personal Access Token'
    required: false

outputs:
  published-count:
    description: 'Number of extensions successfully published'
    value: ${{ steps.publish.outputs.published-count }}
  skipped-count:
    description: 'Number of extensions skipped'
    value: ${{ steps.publish.outputs.skipped-count }}
  summary:
    description: 'Publishing summary message'
    value: ${{ steps.publish.outputs.summary }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ "${{ inputs.marketplace }}" != "vscode" ] && [ "${{ inputs.marketplace }}" != "vscodium" ]; then
          echo "::error::Invalid marketplace. Must be 'vscode' or 'vscodium'"
          exit 1
        fi
        
        if [ "${{ inputs.marketplace }}" == "vscode" ] && [ -z "${{ inputs.vsce-token }}" ]; then
          echo "::error::vsce-token is required for VS Code Marketplace"
          exit 1
        fi
        
        if [ "${{ inputs.marketplace }}" == "vscodium" ] && [ -z "${{ inputs.ovsx-token }}" ]; then
          echo "::error::ovsx-token is required for Open VSX Registry"
          exit 1
        fi

    - name: Publish extensions
      id: publish
      shell: bash
      env:
        VSCE_PAT: ${{ inputs.vsce-token }}
        OVSX_PAT: ${{ inputs.ovsx-token }}
      run: |
        chmod +x scripts/publish-extensions.sh
        ./scripts/publish-extensions.sh "${{ inputs.marketplace }}" "${{ inputs.packages-path }}" "${{ inputs.dist-path }}"
